/* Seed the di_questions collection from the extracted JSON files.
 * Source: Nishit Sinha LRDI for the CAT (Pearson, 6e), Part 2 Section 2
 * "Practising Data Interpretation" — Ch 20 Foundation (8 exercises),
 * Ch 21 Moderate (11), Ch 22 Advanced (4). Each practice exercise => one DI test,
 * numbered 1..N globally and tagged with its tier. Chart/table visuals are cropped
 * PNGs under public/di/<tier>/ referenced as markdown images inside context_passage.
 * Generated by .varc_extract/extract_di.py.
 * Run:  node api/seed_di.js
 */
const mongoose = require('mongoose');
const fs = require('fs');
const path = require('path');
require('dotenv').config({ path: path.join(__dirname, '..', '.env.local') });
require('dotenv').config({ path: path.join(__dirname, '..', '.env') });

const QDIR = path.join(__dirname, '..', 'chapter_questions');
const PUBLIC = path.join(__dirname, '..', 'public');
const SOURCE = 'Nishit Sinha LRDI (Pearson, 6e)';

// Chart/table crops are NOT committed to the repo. The JSON keeps a lightweight image
// path (e.g. /di/fnd/1-s1.png); at seed time we read that PNG from public/ and inline it
// as a base64 data-URI into context_passage, so the image lives in MongoDB. MathText
// renders data: URIs (same as the set-theory Venn diagrams). Caselet passages are text
// and pass through unchanged.
let embedded = 0, missing = 0;
function embedImages(cp) {
  if (!cp) return cp;
  return cp.replace(/!\[([^\]]*)\]\((\/di\/[^)\s]+\.png)\)/g, (m, alt, url) => {
    const file = path.join(PUBLIC, url);
    if (!fs.existsSync(file)) { missing++; console.warn('  ! missing image, keeping path:', url); return m; }
    const b64 = fs.readFileSync(file).toString('base64');
    embedded++;
    return `![${alt}](data:image/png;base64,${b64})`;
  });
}

(async () => {
  await mongoose.connect(process.env.MONGODB_STRING, { bufferCommands: false });
  const col = mongoose.connection.db.collection('di_questions');
  const sessions = mongoose.connection.db.collection('di_sessions');

  const files = fs
    .readdirSync(QDIR)
    .filter(f => /^di_(foundation|moderate|advanced)_\d+\.json$/.test(f))
    .sort();

  const del = await col.deleteMany({ source: SOURCE });
  console.log(`Deleted ${del.deletedCount} existing DI questions`);

  let total = 0;
  const byTier = {};
  for (const file of files) {
    const docs = JSON.parse(fs.readFileSync(path.join(QDIR, file), 'utf8'));
    if (!docs.length) continue;
    const now = new Date();
    const ins = await col.insertMany(
      docs.map(d => ({
        ...d,
        context_passage: embedImages(d.context_passage),
        source: d.source || SOURCE,
        createdAt: now, updatedAt: now,
      })),
      { ordered: false }
    );
    total += ins.insertedCount;
    const tier = docs[0].tier;
    byTier[tier] = (byTier[tier] || 0) + ins.insertedCount;
    console.log(`${file}: inserted ${ins.insertedCount} (test ${docs[0].test}, ${tier})`);
  }

  // Sessions reference question _ids that change on reseed — clear them.
  const cleared = await sessions.deleteMany({});
  console.log(`Cleared ${cleared.deletedCount} stale DI sessions`);

  console.log(`\ndi_questions total: ${total}`, byTier);
  console.log(`Images embedded as base64 data-URIs: ${embedded}` + (missing ? ` (${missing} missing, kept as path)` : ''));
  await mongoose.disconnect();
  process.exit(0);
})().catch(e => { console.error(e); process.exit(1); });
