/* Seed the di_questions collection from the extracted JSON files.
 * Source: Nishit Sinha LRDI for the CAT (Pearson, 6e), Part 2 Section 2
 * "Practising Data Interpretation" — Ch 20 Foundation (8), Ch 21 Moderate (11),
 * Ch 22 Advanced (4). Each practice exercise => one DI test.
 *
 * Chart/table crops are COMMITTED static files under public/di/ (served by Vercel at
 * /di/<tier>/<file>.png). context_passage keeps the image as a markdown path, e.g.
 * ![data set 1](/di/fnd/1-s1.png), which MathText renders as an <img>. This is robust to
 * the DB being re-seeded by any process/build — the path always resolves to the committed
 * file. (Earlier attempts to store images as base64 in the DB broke whenever a re-seed ran
 * without the local crops.) Text caselets pass through unchanged.
 * Generated by .varc_extract/extract_di.py.  Run:  node api/seed_di.js
 */
const mongoose = require('mongoose');
const fs = require('fs');
const path = require('path');
require('dotenv').config({ path: path.join(__dirname, '..', '.env.local') });
require('dotenv').config({ path: path.join(__dirname, '..', '.env') });

const QDIR = path.join(__dirname, '..', 'chapter_questions');
const SOURCE = 'Nishit Sinha LRDI (Pearson, 6e)';

(async () => {
  await mongoose.connect(process.env.MONGODB_STRING, { bufferCommands: false });
  const col = mongoose.connection.db.collection('di_questions');
  const sessions = mongoose.connection.db.collection('di_sessions');
  await mongoose.connection.db.collection('di_images').deleteMany({}).catch(() => {});
  const del = await col.deleteMany({});
  console.log(`Deleted ${del.deletedCount} existing DI questions`);

  const files = fs.readdirSync(QDIR)
    .filter(f => /^di_(foundation|moderate|advanced)_\d+\.json$/.test(f)).sort();

  let total = 0;
  const byTier = {};
  for (const file of files) {
    const docs = JSON.parse(fs.readFileSync(path.join(QDIR, file), 'utf8'));
    if (!docs.length) continue;
    const now = new Date();
    const out = docs.map(d => ({ ...d, source: d.source || SOURCE, createdAt: now, updatedAt: now }));
    await col.insertMany(out, { ordered: false });
    total += out.length;
    byTier[docs[0].tier] = (byTier[docs[0].tier] || 0) + out.length;
    console.log(`${file}: inserted ${out.length} (test ${docs[0].test}, ${docs[0].tier})`);
  }

  const cleared = await sessions.deleteMany({});
  console.log(`Cleared ${cleared.deletedCount} stale DI sessions`);
  console.log(`\ndi_questions total: ${total}`, byTier);
  await mongoose.disconnect();
  process.exit(0);
})().catch(e => { console.error(e); process.exit(1); });
