/* Seed the di_questions collection from the extracted JSON files.
 * Source: Nishit Sinha LRDI for the CAT (Pearson, 6e), Part 2 Section 2
 * "Practising Data Interpretation" — Ch 20 Foundation (8), Ch 21 Moderate (11),
 * Ch 22 Advanced (4). Each practice exercise => one DI test.
 *
 * Chart/table crops are NOT committed (public/di/ is gitignored). The JSON keeps a
 * lightweight path (e.g. /di/fnd/1-s1.png); at seed time we read that PNG and inline it
 * as a base64 data-URI directly into context_passage, so the image lives in MongoDB and
 * rides the (working) questions JSON response — no separate binary endpoint (Vercel's
 * serverless adapter does not reliably serve raw binary). MathText renders data: URIs,
 * same as the set-theory Venn diagrams. Text caselets pass through unchanged.
 * Generated by .varc_extract/extract_di.py.  Run:  node api/seed_di.js
 */
const mongoose = require('mongoose');
const fs = require('fs');
const path = require('path');
require('dotenv').config({ path: path.join(__dirname, '..', '.env.local') });
require('dotenv').config({ path: path.join(__dirname, '..', '.env') });

const QDIR = path.join(__dirname, '..', 'chapter_questions');
const PUBLIC = path.join(__dirname, '..', 'public');
const SOURCE = 'Nishit Sinha LRDI (Pearson, 6e)';

let embedded = 0, missing = 0;
function embedImages(cp) {
  if (!cp) return cp;
  return cp.replace(/!\[([^\]]*)\]\((\/di\/[^)\s]+\.png)\)/g, (m, alt, url) => {
    const file = path.join(PUBLIC, url);
    if (!fs.existsSync(file)) { missing++; console.warn('  ! missing image, keeping path:', url); return m; }
    embedded++;
    return `![${alt}](data:image/png;base64,${fs.readFileSync(file).toString('base64')})`;
  });
}

(async () => {
  await mongoose.connect(process.env.MONGODB_STRING, { bufferCommands: false });
  const col = mongoose.connection.db.collection('di_questions');
  const sessions = mongoose.connection.db.collection('di_sessions');
  // Drop the legacy image collection + any stale docs from earlier seed formats.
  await mongoose.connection.db.collection('di_images').deleteMany({}).catch(() => {});
  const del = await col.deleteMany({});
  console.log(`Deleted ${del.deletedCount} existing DI questions`);

  const files = fs.readdirSync(QDIR)
    .filter(f => /^di_(foundation|moderate|advanced)_\d+\.json$/.test(f)).sort();

  let total = 0, maxResp = 0, maxRespTest = null;
  const byTier = {};
  for (const file of files) {
    const docs = JSON.parse(fs.readFileSync(path.join(QDIR, file), 'utf8'));
    if (!docs.length) continue;
    const now = new Date();
    const out = docs.map(d => ({ ...d, context_passage: embedImages(d.context_passage), source: d.source || SOURCE, createdAt: now, updatedAt: now }));
    await col.insertMany(out, { ordered: false });
    total += out.length;
    byTier[docs[0].tier] = (byTier[docs[0].tier] || 0) + out.length;
    // Approx /api/di/start response size for this test (sum of context_passage bytes).
    const resp = out.reduce((s, d) => s + Buffer.byteLength(d.context_passage || '', 'utf8'), 0);
    if (resp > maxResp) { maxResp = resp; maxRespTest = docs[0].test; }
    console.log(`${file}: inserted ${out.length} (test ${docs[0].test}, ${docs[0].tier}), ~${Math.round(resp / 1024)}KB context`);
  }

  const cleared = await sessions.deleteMany({});
  console.log(`Cleared ${cleared.deletedCount} stale DI sessions`);
  console.log(`\ndi_questions total: ${total}`, byTier);
  console.log(`Images embedded as base64 data-URIs: ${embedded}` + (missing ? ` (${missing} missing)` : ''));
  console.log(`Largest per-test context payload: ~${Math.round(maxResp / 1024)}KB (test ${maxRespTest}) — Vercel limit ~4.5MB`);
  await mongoose.disconnect();
  process.exit(0);
})().catch(e => { console.error(e); process.exit(1); });
