import { Question } from './types';

const makeQ = (
  id: string, code: string, section: 'VARC' | 'DILR' | 'QA',
  type: 'MCQ' | 'TITA', topic: string, subtopic: string,
  text: string, options: { label: string; text: string }[] | null,
  correct: string, setId: string | null = null, setPos: number | null = null,
  passage: string | null = null, num: number = 1
): Question => ({
  _id: id, question_code: code, section, question_type: type,
  topic, subtopic, set_id: setId, set_position: setPos,
  context_passage: passage, question_text: text, options,
  correct_answer: correct, marks_correct: 3, marks_incorrect: type === 'MCQ' ? -1 : 0,
  explanation: 'See solution.', difficulty: 'Medium', question_number: num,
  tags: [], is_image_based: false, image_url: null,
});

const rcPassage = `A new study challenges the long-held assumption that sleep is a passive process. Researchers have found that during sleep, the brain actively consolidates memories, flushes out toxins accumulated during the day, and strengthens neural connections. The glymphatic system, a network of channels surrounding blood vessels, expands during sleep to allow cerebrospinal fluid to wash through the brain, clearing metabolic waste including proteins associated with Alzheimer's disease.

The study also reveals that different sleep stages serve distinct functions. Rapid Eye Movement (REM) sleep, characterised by vivid dreaming, appears crucial for emotional memory processing. Non-REM deep sleep, on the other hand, seems essential for declarative memory consolidation — the type involved in learning facts and events. Disrupting either stage has measurable cognitive consequences.

These findings have implications for public health. Chronic sleep deprivation, common in modern societies, may accelerate neurological decline. The researchers argue that sleep hygiene — consistent schedules, dark quiet environments, and limited screen exposure before bed — should be considered as important as diet and exercise for long-term brain health.`;

const diPassage = `Eight friends — A, B, C, D, E, F, G, and H — are sitting around a circular table. Each person has a different profession: Doctor, Engineer, Lawyer, Teacher, Architect, Banker, Pilot, and Chef. A sits opposite to the Doctor. B is a Pilot and sits two seats to the right of A. C is a Teacher and sits immediately to the left of B. D is not adjacent to A. E is a Banker and sits opposite to F. G is an Architect. H is a Chef and sits immediately to the right of A.`;

export const DEMO_QUESTIONS: Record<'VARC' | 'DILR' | 'QA', Question[]> = {
  VARC: [
    // RC Set (set_id: rc1), 4 questions
    makeQ('v1','V001','VARC','MCQ','RC','Comprehension','According to the passage, what does the glymphatic system primarily do during sleep?',[{label:'A',text:'Consolidates emotional memories'},{label:'B',text:'Clears metabolic waste including Alzheimer-linked proteins'},{label:'C',text:'Strengthens REM sleep patterns'},{label:'D',text:'Regulates body temperature'}],'B','rc1',1,rcPassage,1),
    makeQ('v2','V002','VARC','MCQ','RC','Comprehension','Which sleep stage is described as crucial for emotional memory processing?',[{label:'A',text:'Non-REM deep sleep'},{label:'B',text:'Light sleep'},{label:'C',text:'REM sleep'},{label:'D',text:'Transitional sleep'}],'C','rc1',2,rcPassage,2),
    makeQ('v3','V003','VARC','MCQ','RC','Inference','The author most likely uses the phrase "sleep hygiene" to mean:',[{label:'A',text:'Cleanliness practices before bed'},{label:'B',text:'Habits and conditions that promote healthy sleep'},{label:'C',text:'Medical treatments for sleep disorders'},{label:'D',text:'The cleaning function of the glymphatic system'}],'B','rc1',3,rcPassage,3),
    makeQ('v4','V004','VARC','MCQ','RC','Comprehension','Which of the following best summarises the main argument of the passage?',[{label:'A',text:'Sleep deprivation causes Alzheimer\'s disease'},{label:'B',text:'REM sleep is more important than non-REM sleep'},{label:'C',text:'Sleep is an active, health-critical process that modern society undervalues'},{label:'D',text:'Diet and exercise are less important than sleep'}],'C','rc1',4,rcPassage,4),
    // RC Set 2 (set_id: rc2), 3 questions
    makeQ('v5','V005','VARC','MCQ','RC','Comprehension','The term "declarative memory" as used in the passage refers to:',[{label:'A',text:'Memory of emotional experiences'},{label:'B',text:'Memory of facts and events'},{label:'C',text:'Procedural or skill-based memory'},{label:'D',text:'Short-term working memory'}],'B','rc2',1,'Declarative memory, also known as explicit memory, encompasses memories that can be consciously recalled. This includes both episodic memory (personal experiences) and semantic memory (general knowledge and facts). Researchers distinguish this from procedural memory, which involves skills and habits learned through repetition, and from emotional memory which is processed via the amygdala. Studies consistently show that declarative memory is most vulnerable to sleep deprivation, with recall accuracy declining sharply after even one night of disrupted sleep.',5),
    makeQ('v6','V006','VARC','MCQ','RC','Inference','Based on the passage, which of the following can be inferred about procedural memory?',[{label:'A',text:'It is not processed during sleep at all'},{label:'B',text:'It is the same as declarative memory'},{label:'C',text:'It involves skills learned through repetition, distinct from declarative memory'},{label:'D',text:'It is more important than semantic memory'}],'C','rc2',2,'Declarative memory, also known as explicit memory, encompasses memories that can be consciously recalled. This includes both episodic memory (personal experiences) and semantic memory (general knowledge and facts). Researchers distinguish this from procedural memory, which involves skills and habits learned through repetition, and from emotional memory which is processed via the amygdala. Studies consistently show that declarative memory is most vulnerable to sleep deprivation, with recall accuracy declining sharply after even one night of disrupted sleep.',6),
    makeQ('v7','V007','VARC','MCQ','RC','Vocabulary','The word "encompasses" in the passage is closest in meaning to:',[{label:'A',text:'Excludes'},{label:'B',text:'Includes and contains'},{label:'C',text:'Challenges'},{label:'D',text:'Replaces'}],'B','rc2',3,'Declarative memory, also known as explicit memory, encompasses memories that can be consciously recalled. This includes both episodic memory (personal experiences) and semantic memory (general knowledge and facts). Researchers distinguish this from procedural memory, which involves skills and habits learned through repetition, and from emotional memory which is processed via the amygdala. Studies consistently show that declarative memory is most vulnerable to sleep deprivation, with recall accuracy declining sharply after even one night of disrupted sleep.',7),
    // Standalone VA questions
    makeQ('v8','V008','VARC','MCQ','VA','Para-jumble','Which of the following statements, if true, would most weaken the claim that social media increases loneliness?',[{label:'A',text:'Studies show that heavy social media users report higher loneliness scores'},{label:'B',text:'People who use social media more tend to also meet friends in person more often'},{label:'C',text:'Social media platforms profit from keeping users engaged'},{label:'D',text:'Screen time displaces time previously spent sleeping'}],'B',null,null,null,8),
    makeQ('v9','V009','VARC','MCQ','VA','Critical Reasoning','Choose the sentence that does NOT fit in the following paragraph about urban planning: (A) Cities are increasingly prioritising pedestrian zones. (B) Cycling infrastructure reduces car dependency. (C) The invention of the steam engine revolutionised travel. (D) Green spaces improve mental health in dense urban areas.',[{label:'A',text:'Sentence A'},{label:'B',text:'Sentence B'},{label:'C',text:'Sentence C'},{label:'D',text:'Sentence D'}],'C',null,null,null,9),
    makeQ('v10','V010','VARC','MCQ','VA','Para-summary','The author argues that economic growth without equitable distribution leads to social instability. Which of the following best paraphrases this idea?',[{label:'A',text:'Rich nations always become unstable'},{label:'B',text:'Growth that benefits only a few ultimately destabilises society'},{label:'C',text:'Equal distribution always causes growth'},{label:'D',text:'Social stability requires zero economic growth'}],'B',null,null,null,10),
    makeQ('v11','V011','VARC','MCQ','VA','Odd Sentence','Four sentences are given. Three form a coherent paragraph. Identify the odd one out. (A) The ozone layer shields Earth from harmful UV radiation. (B) Antarctica has recorded significant thinning of the ozone layer. (C) UV radiation helps plants synthesise vitamin D. (D) Chlorofluorocarbons are the primary cause of ozone depletion.',[{label:'A',text:'A'},{label:'B',text:'B'},{label:'C',text:'C'},{label:'D',text:'D'}],'C',null,null,null,11),
    makeQ('v12','V012','VARC','MCQ','VA','Inference','A politician says: "We must either raise taxes or cut spending." A critic responds: "There is a third option — stimulating growth to increase revenue without either." The critic is pointing out:',[{label:'A',text:'A false dilemma in the politician\'s statement'},{label:'B',text:'That taxes should never be raised'},{label:'C',text:'That spending cuts are always harmful'},{label:'D',text:'A factual error in the politician\'s claim'}],'A',null,null,null,12),
    // RC Set 3 (set_id: rc3), 4 questions
    makeQ('v13','V013','VARC','MCQ','RC','Comprehension','The passage primarily discusses:',[{label:'A',text:'The dangers of artificial intelligence'},{label:'B',text:'How language shapes thought and cognition'},{label:'C',text:'The history of linguistics as a discipline'},{label:'D',text:'Grammar rules across different languages'}],'B','rc3',1,'The Sapir-Whorf hypothesis, also known as linguistic relativity, posits that the language one speaks shapes the way one thinks and perceives the world. Proponents argue that speakers of languages with rich tense systems think about time differently from those whose languages encode time loosely. Similarly, languages with many colour terms may lead speakers to more readily discriminate between hues. Critics, however, contend that while language may influence certain cognitive tasks, it does not fundamentally determine thought — people can think about concepts for which they lack words, and universal cognitive capacities exist across cultures.',13),
    makeQ('v14','V014','VARC','MCQ','RC','Inference','Which of the following best describes the relationship between proponents and critics of the hypothesis as presented in the passage?',[{label:'A',text:'Both agree language shapes thought completely'},{label:'B',text:'Proponents say language shapes thought; critics say the effect is limited'},{label:'C',text:'Critics support the hypothesis, proponents reject it'},{label:'D',text:'Both agree the hypothesis has been disproven'}],'B','rc3',2,'The Sapir-Whorf hypothesis, also known as linguistic relativity, posits that the language one speaks shapes the way one thinks and perceives the world. Proponents argue that speakers of languages with rich tense systems think about time differently from those whose languages encode time loosely. Similarly, languages with many colour terms may lead speakers to more readily discriminate between hues. Critics, however, contend that while language may influence certain cognitive tasks, it does not fundamentally determine thought — people can think about concepts for which they lack words, and universal cognitive capacities exist across cultures.',14),
    makeQ('v15','V015','VARC','MCQ','RC','Vocabulary','The word "posits" in the passage most nearly means:',[{label:'A',text:'Disproves'},{label:'B',text:'Assumes or claims as a starting point'},{label:'C',text:'Ignores'},{label:'D',text:'Measures experimentally'}],'B','rc3',3,'The Sapir-Whorf hypothesis, also known as linguistic relativity, posits that the language one speaks shapes the way one thinks and perceives the world. Proponents argue that speakers of languages with rich tense systems think about time differently from those whose languages encode time loosely. Similarly, languages with many colour terms may lead speakers to more readily discriminate between hues. Critics, however, contend that while language may influence certain cognitive tasks, it does not fundamentally determine thought — people can think about concepts for which they lack words, and universal cognitive capacities exist across cultures.',15),
    makeQ('v16','V016','VARC','MCQ','RC','Inference','According to the critics mentioned, universal cognitive capacities across cultures suggest that:',[{label:'A',text:'All languages are equally complex'},{label:'B',text:'Language determines all aspects of thought'},{label:'C',text:'Thought is not entirely dependent on the language one speaks'},{label:'D',text:'Colour perception is the same across cultures'}],'C','rc3',4,'The Sapir-Whorf hypothesis, also known as linguistic relativity, posits that the language one speaks shapes the way one thinks and perceives the world. Proponents argue that speakers of languages with rich tense systems think about time differently from those whose languages encode time loosely. Similarly, languages with many colour terms may lead speakers to more readily discriminate between hues. Critics, however, contend that while language may influence certain cognitive tasks, it does not fundamentally determine thought — people can think about concepts for which they lack words, and universal cognitive capacities exist across cultures.',16),
    // More standalone VA
    makeQ('v17','V017','VARC','MCQ','VA','Para-jumble','Arrange the following sentences to form a coherent paragraph: (P) This makes scientific literacy essential for modern citizens. (Q) Science affects every aspect of modern life, from medicine to climate policy. (R) Yet surveys consistently show poor public understanding of basic scientific concepts. (S) Without it, people cannot evaluate evidence or make informed decisions.',[{label:'A',text:'QRPS'},{label:'B',text:'PQRS'},{label:'C',text:'RSPQ'},{label:'D',text:'QRSP'}],'D',null,null,null,17),
    makeQ('v18','V018','VARC','MCQ','VA','Critical Reasoning','Which of the following most logically completes the argument? "All mammals are warm-blooded. Dolphins are mammals. Therefore, ___."',[{label:'A',text:'Dolphins breathe underwater'},{label:'B',text:'Dolphins are warm-blooded'},{label:'C',text:'All warm-blooded animals are dolphins'},{label:'D',text:'Dolphins are fish'}],'B',null,null,null,18),
    makeQ('v19','V019','VARC','MCQ','VA','Inference','A company advertises: "Nine out of ten dentists recommend our toothpaste." Which of the following questions most undermines the credibility of this claim?',[{label:'A',text:'How many people use the toothpaste daily?'},{label:'B',text:'How were the dentists selected and what were they asked?'},{label:'C',text:'What is the price of the toothpaste?'},{label:'D',text:'Does the toothpaste contain fluoride?'}],'B',null,null,null,19),
    makeQ('v20','V020','VARC','MCQ','VA','Para-summary','Identify the statement that is NOT an assumption underlying: "Students who study more hours get better grades."',[{label:'A',text:'Study hours are the only factor affecting grades'},{label:'B',text:'All students study with equal efficiency per hour'},{label:'C',text:'Better grades reflect better learning'},{label:'D',text:'Grades are a valid measure of academic performance'}],'A',null,null,null,20),
    makeQ('v21','V021','VARC','MCQ','VA','Odd Sentence','Which sentence is the odd one out in a paragraph about digital privacy? (A) End-to-end encryption secures message content. (B) GDPR regulates data collection in Europe. (C) Photosynthesis converts sunlight into chemical energy. (D) Companies must obtain user consent before tracking.',[{label:'A',text:'A'},{label:'B',text:'B'},{label:'C',text:'C'},{label:'D',text:'D'}],'C',null,null,null,21),
    // TITA questions
    makeQ('v22','V022','VARC','TITA','VA','Grammar','How many grammatically correct sentences are there in the following group? (I) Neither the manager nor the employees was present. (II) Each of the students has submitted their assignment. (III) The committee have decided to postpone the meeting. (IV) She is one of those people who believes in hard work. Enter the number.',null,'2',null,null,null,22),
    makeQ('v23','V023','VARC','TITA','VA','Vocabulary','The passage uses five words from the following list: ephemeral, lucid, tenacious, opaque, verbose, concise. How many of the words in the list are antonyms of each other in pairs? Enter the number.',null,'3',null,null,null,23),
    makeQ('v24','V024','VARC','TITA','VA','Critical Reasoning','A speaker makes 4 logical arguments. Of these, 2 contain circular reasoning and 1 contains a false dichotomy. How many of the 4 arguments contain a logical fallacy?',null,'3',null,null,null,24),
  ],

  DILR: [
    // DI Set 1 (set_id: di1), 5 questions
    makeQ('d1','D001','DILR','MCQ','DI','Tables','How many friends are sitting between A and H (going clockwise)?',[{label:'A',text:'1'},{label:'B',text:'2'},{label:'C',text:'3'},{label:'D',text:'4'}],'C','di1',1,diPassage,1),
    makeQ('d2','D002','DILR','MCQ','DI','Tables','Who is sitting opposite to B?',[{label:'A',text:'D'},{label:'B',text:'E'},{label:'C',text:'F'},{label:'D',text:'G'}],'A','di1',2,diPassage,2),
    makeQ('d3','D003','DILR','MCQ','DI','Tables','What is the profession of the person sitting opposite to H?',[{label:'A',text:'Doctor'},{label:'B',text:'Lawyer'},{label:'C',text:'Engineer'},{label:'D',text:'Banker'}],'C','di1',3,diPassage,3),
    makeQ('d4','D004','DILR','MCQ','DI','Tables','Which two friends are adjacent to G?',[{label:'A',text:'A and B'},{label:'B',text:'C and D'},{label:'C',text:'D and E'},{label:'D',text:'F and H'}],'C','di1',4,diPassage,4),
    makeQ('d5','D005','DILR','MCQ','DI','Tables','Who is the Doctor?',[{label:'A',text:'B'},{label:'B',text:'D'},{label:'C',text:'F'},{label:'D',text:'G'}],'B','di1',5,diPassage,5),
    // LR Set 2 (set_id: lr1), 5 questions
    makeQ('d6','D006','DILR','MCQ','LR','Arrangements','Study the table: Product sales (units) for Q1-Q4: Laptop(120,145,130,160), Phone(200,220,195,240), Tablet(80,75,90,85). Which product had the highest growth from Q1 to Q4?',[{label:'A',text:'Laptop'},{label:'B',text:'Phone'},{label:'C',text:'Tablet'},{label:'D',text:'All equal'}],'A','lr1',1,'A retail chain tracks quarterly sales of three product categories: Laptops, Phones, and Tablets. In Q1, Laptops sold 120 units, Phones 200 units, and Tablets 80 units. In Q2, Laptops sold 145, Phones 220, and Tablets 75. In Q3, Laptops sold 130, Phones 195, and Tablets 90. In Q4, Laptops sold 160, Phones 240, and Tablets 85. The selling prices are Laptop ₹60,000, Phone ₹25,000, and Tablet ₹35,000.',6),
    makeQ('d7','D007','DILR','MCQ','LR','Arrangements','What is the total revenue (in ₹ lakhs) from Phone sales in Q2? (Price: ₹25,000 per unit)',[{label:'A',text:'₹48 lakhs'},{label:'B',text:'₹54 lakhs'},{label:'C',text:'₹55 lakhs'},{label:'D',text:'₹60 lakhs'}],'C','lr1',2,'A retail chain tracks quarterly sales of three product categories: Laptops, Phones, and Tablets. In Q1, Laptops sold 120 units, Phones 200 units, and Tablets 80 units. In Q2, Laptops sold 145, Phones 220, and Tablets 75. In Q3, Laptops sold 130, Phones 195, and Tablets 90. In Q4, Laptops sold 160, Phones 240, and Tablets 85. The selling prices are Laptop ₹60,000, Phone ₹25,000, and Tablet ₹35,000.',7),
    makeQ('d8','D008','DILR','MCQ','LR','Arrangements','In which quarter was the combined sale of all three products highest?',[{label:'A',text:'Q1'},{label:'B',text:'Q2'},{label:'C',text:'Q3'},{label:'D',text:'Q4'}],'D','lr1',3,'A retail chain tracks quarterly sales of three product categories: Laptops, Phones, and Tablets. In Q1, Laptops sold 120 units, Phones 200 units, and Tablets 80 units. In Q2, Laptops sold 145, Phones 220, and Tablets 75. In Q3, Laptops sold 130, Phones 195, and Tablets 90. In Q4, Laptops sold 160, Phones 240, and Tablets 85. The selling prices are Laptop ₹60,000, Phone ₹25,000, and Tablet ₹35,000.',8),
    makeQ('d9','D009','DILR','MCQ','LR','Arrangements','By what percentage did Tablet sales increase from Q3 to Q4?',[{label:'A',text:'−5.6%'},{label:'B',text:'+5.6%'},{label:'C',text:'−6.7%'},{label:'D',text:'+6.7%'}],'A','lr1',4,'A retail chain tracks quarterly sales of three product categories: Laptops, Phones, and Tablets. In Q1, Laptops sold 120 units, Phones 200 units, and Tablets 80 units. In Q2, Laptops sold 145, Phones 220, and Tablets 75. In Q3, Laptops sold 130, Phones 195, and Tablets 90. In Q4, Laptops sold 160, Phones 240, and Tablets 85. The selling prices are Laptop ₹60,000, Phone ₹25,000, and Tablet ₹35,000.',9),
    makeQ('d10','D010','DILR','MCQ','LR','Arrangements','What is the ratio of total Laptop revenue to total Tablet revenue across all four quarters?',[{label:'A',text:'3:1'},{label:'B',text:'4:1'},{label:'C',text:'555:330'},{label:'D',text:'2:1'}],'C','lr1',5,'A retail chain tracks quarterly sales of three product categories: Laptops, Phones, and Tablets. In Q1, Laptops sold 120 units, Phones 200 units, and Tablets 80 units. In Q2, Laptops sold 145, Phones 220, and Tablets 75. In Q3, Laptops sold 130, Phones 195, and Tablets 90. In Q4, Laptops sold 160, Phones 240, and Tablets 85. The selling prices are Laptop ₹60,000, Phone ₹25,000, and Tablet ₹35,000.',10),
    // LR Set 3 (set_id: lr2), 5 questions
    makeQ('d11','D011','DILR','MCQ','LR','Puzzles','Five students A, B, C, D, E scored different marks. A scored more than B. C scored less than D but more than E. B scored more than D. Who scored the highest?',[{label:'A',text:'A'},{label:'B',text:'B'},{label:'C',text:'C'},{label:'D',text:'D'}],'A','lr2',1,null,11),
    makeQ('d12','D012','DILR','MCQ','LR','Puzzles','Using the same ordering (A > B > D > C > E), who scored second lowest?',[{label:'A',text:'B'},{label:'B',text:'C'},{label:'C',text:'D'},{label:'D',text:'E'}],'B','lr2',2,null,12),
    makeQ('d13','D013','DILR','MCQ','LR','Puzzles','If each student\'s score is a distinct integer from 1 to 5, what is B\'s score?',[{label:'A',text:'2'},{label:'B',text:'3'},{label:'C',text:'4'},{label:'D',text:'5'}],'C','lr2',3,null,13),
    makeQ('d14','D014','DILR','MCQ','LR','Puzzles','How many students scored below B?',[{label:'A',text:'1'},{label:'B',text:'2'},{label:'C',text:'3'},{label:'D',text:'4'}],'C','lr2',4,null,14),
    makeQ('d15','D015','DILR','MCQ','LR','Puzzles','If A scored 5 and E scored 1, what is the sum of scores of B and C?',[{label:'A',text:'5'},{label:'B',text:'6'},{label:'C',text:'7'},{label:'D',text:'8'}],'C','lr2',5,null,15),
    // Standalone MCQs
    makeQ('d16','D016','DILR','MCQ','LR','Coding','In a code, MANGO = 41234 and GRAPE = 34815. What is the code for POEM?',[{label:'A',text:'8412'},{label:'B',text:'8421'},{label:'C',text:'4821'},{label:'D',text:'1482'}],'A',null,null,null,16),
    // TITA questions
    makeQ('d17','D017','DILR','TITA','DI','Bar Charts','A train travels 300 km at 60 km/h, then 200 km at 80 km/h. What is its average speed (in km/h) for the entire journey? Enter a number.',null,'68',null,null,null,17),
    makeQ('d18','D018','DILR','TITA','DI','Bar Charts','In a class of 40, 25 play cricket, 18 play football, and 10 play both. How many play neither?',null,'7',null,null,null,18),
    makeQ('d19','D019','DILR','TITA','LR','Arrangements','A password consists of 3 distinct digits from 1-9. How many passwords are possible if the digits must be in ascending order?',null,'84',null,null,null,19),
    makeQ('d20','D020','DILR','TITA','DI','Tables','In a survey, 60% like tea, 50% like coffee, and 20% like neither. What percentage like both?',null,'30',null,null,null,20),
  ],

  QA: [
    makeQ('q1','Q001','QA','MCQ','Arithmetic','Percentages','A shopkeeper sells an article at a 20% profit. If the cost price is ₹250, what is the selling price?',[{label:'A',text:'₹290'},{label:'B',text:'₹300'},{label:'C',text:'₹310'},{label:'D',text:'₹320'}],'B',null,null,null,1),
    makeQ('q2','Q002','QA','MCQ','Algebra','Linear Equations','If 3x + 5 = 20, what is the value of 6x − 4?',[{label:'A',text:'22'},{label:'B',text:'24'},{label:'C',text:'26'},{label:'D',text:'28'}],'C',null,null,null,2),
    makeQ('q3','Q003','QA','MCQ','Geometry','Triangles','In a right-angled triangle, the two legs are 6 cm and 8 cm. What is the length of the hypotenuse?',[{label:'A',text:'10 cm'},{label:'B',text:'11 cm'},{label:'C',text:'12 cm'},{label:'D',text:'14 cm'}],'A',null,null,null,3),
    makeQ('q4','Q004','QA','MCQ','Number Theory','Divisibility','What is the LCM of 12, 18, and 24?',[{label:'A',text:'48'},{label:'B',text:'72'},{label:'C',text:'96'},{label:'D',text:'144'}],'B',null,null,null,4),
    makeQ('q5','Q005','QA','MCQ','Arithmetic','Speed-Distance','Two trains of lengths 120 m and 80 m are moving in opposite directions at 50 km/h and 40 km/h. How many seconds do they take to cross each other?',[{label:'A',text:'8 sec'},{label:'B',text:'9 sec'},{label:'C',text:'10 sec'},{label:'D',text:'12 sec'}],'A',null,null,null,5),
    makeQ('q6','Q006','QA','MCQ','Algebra','Quadratic Equations','The roots of x² − 5x + 6 = 0 are:',[{label:'A',text:'2 and 4'},{label:'B',text:'2 and 3'},{label:'C',text:'3 and 4'},{label:'D',text:'1 and 6'}],'B',null,null,null,6),
    makeQ('q7','Q007','QA','MCQ','Arithmetic','Simple Interest','What is the simple interest on ₹5000 at 8% per annum for 3 years?',[{label:'A',text:'₹1000'},{label:'B',text:'₹1200'},{label:'C',text:'₹1500'},{label:'D',text:'₹2000'}],'B',null,null,null,7),
    makeQ('q8','Q008','QA','MCQ','Geometry','Circles','A circle has radius 7 cm. What is its area? (Use π = 22/7)',[{label:'A',text:'144 cm²'},{label:'B',text:'154 cm²'},{label:'C',text:'164 cm²'},{label:'D',text:'176 cm²'}],'B',null,null,null,8),
    makeQ('q9','Q009','QA','MCQ','Number Theory','Prime Numbers','Which of the following is a prime number?',[{label:'A',text:'91'},{label:'B',text:'93'},{label:'C',text:'97'},{label:'D',text:'99'}],'C',null,null,null,9),
    makeQ('q10','Q010','QA','MCQ','Arithmetic','Profit & Loss','A person buys an item for ₹800 and sells it for ₹1000. What is the profit percentage?',[{label:'A',text:'20%'},{label:'B',text:'22.5%'},{label:'C',text:'25%'},{label:'D',text:'28%'}],'C',null,null,null,10),
    makeQ('q11','Q011','QA','MCQ','Algebra','Logarithms','log₂(64) = ?',[{label:'A',text:'4'},{label:'B',text:'5'},{label:'C',text:'6'},{label:'D',text:'7'}],'C',null,null,null,11),
    makeQ('q12','Q012','QA','MCQ','Arithmetic','Mixtures','A mixture of 40 litres contains milk and water in 3:1. How many litres of water should be added to make the ratio 3:2?',[{label:'A',text:'8'},{label:'B',text:'10'},{label:'C',text:'12'},{label:'D',text:'15'}],'B',null,null,null,12),
    makeQ('q13','Q013','QA','MCQ','Number Theory','HCF','The HCF of 56, 84, and 112 is:',[{label:'A',text:'14'},{label:'B',text:'28'},{label:'C',text:'42'},{label:'D',text:'56'}],'B',null,null,null,13),
    makeQ('q14','Q014','QA','MCQ','Arithmetic','Time & Work','A and B can complete a job in 12 and 18 days respectively. How many days do they take working together?',[{label:'A',text:'6.6 days'},{label:'B',text:'7.2 days'},{label:'C',text:'8 days'},{label:'D',text:'9 days'}],'B',null,null,null,14),
    // TITA questions
    makeQ('q15','Q015','QA','TITA','Arithmetic','Percentages','The price of a commodity increases by 25% and then decreases by 20%. What is the net percentage change?',null,'0',null,null,null,15),
    makeQ('q16','Q016','QA','TITA','Algebra','Equations','Find the value of x if: 2x + 3y = 16 and x − y = 2. What is x?',null,'4',null,null,null,16),
    makeQ('q17','Q017','QA','TITA','Number Theory','Series','What is the sum of the first 10 natural numbers?',null,'55',null,null,null,17),
    makeQ('q18','Q018','QA','TITA','Geometry','Coordinate','The distance between points (3, 4) and (0, 0) is:',null,'5',null,null,null,18),
    makeQ('q19','Q019','QA','TITA','Arithmetic','Compound Interest','What is the compound interest on ₹1000 at 10% per annum for 2 years (compounded annually)?',null,'210',null,null,null,19),
    makeQ('q20','Q020','QA','TITA','Arithmetic','Averages','The average of 5 numbers is 20. If one number 30 is removed, what is the new average?',null,'17.5',null,null,null,20),
    makeQ('q21','Q021','QA','TITA','Algebra','Functions','If f(x) = 2x² − 3x + 1, find f(2).',null,'3',null,null,null,21),
    makeQ('q22','Q022','QA','TITA','Number Theory','Remainders','What is the remainder when 2^10 is divided by 5?',null,'4',null,null,null,22),
  ],
};
